name: hotshots
favicon: null
layout_spectrum: 0.00674
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1e1d'
    - '#ffffff'
    - '#525252'
    - '#b4b4b4'
    - '#969696'
  brandStrength: 1
  lightness: 0.26252923044376075
  saturation: 0.31516854581423104
  rhythmicContrast: 0.9010603129863739
purpose: []
