name: hotshots
favicon: null
layout_spectrum: 0.08056395780295134
typography_spectrum: 0.08616741886362433
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5407712503802031
  lightness: 0.26252923044376075
  saturation: 0.31516854581423104
  rhythmicContrast: 0.9010603129863739
purpose: []
